/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Staff.*;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author ricardorocha
 */
public class Main extends javax.swing.JFrame {
    
    private int staffId;
    private int secretCode;
    private String firstName;
    private String lastName;
    private String email;

    private String newBookingMemberId;
    private String newBookingMemberName;
    private String newBookingDate;
    private String newBookingTime;

    private Boolean staffExists = false;
    private Boolean memberExists;

    Timer timer = new Timer();

    /**
     * Object from Staff class
     */
    Staff staff = new Staff();
    Bookings bookings = new Bookings();
    Members members = new Members();

    /**
     * Creates new form Main
     */
    public Main() {
        
        /**
         * Populate the staff and bookings list.
         */
        staff.populate();
        bookings.populate();
        members.populate();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBookingFrame = new javax.swing.JFrame();
        newBookingPanel = new javax.swing.JPanel();
        newBookingDateLabel = new javax.swing.JLabel();
        newBookingMemberIdInput = new javax.swing.JTextField();
        newBookingTimeLabel = new javax.swing.JLabel();
        newBookingMemberNameLabel = new javax.swing.JLabel();
        newBookingDateInput = new javax.swing.JTextField();
        newBookingMemberNameInput = new javax.swing.JTextField();
        newBookingTimeInput = new javax.swing.JTextField();
        newBookingMemberIdLabel = new javax.swing.JLabel();
        createNewBookingTitle = new javax.swing.JLabel();
        confirmPaid = new javax.swing.JCheckBox();
        fetchUserButton = new javax.swing.JButton();
        memberValid = new javax.swing.JLabel();
        newBookingConfirmButton = new javax.swing.JButton();
        newBookingCancelButton = new javax.swing.JButton();
        newBookingFirstNameLabel = new javax.swing.JLabel();
        newBookingLastNameLabel = new javax.swing.JLabel();
        newBookingJoinedInLabel = new javax.swing.JLabel();
        newBookingPostCodeLabel = new javax.swing.JLabel();
        newBookingWarningMessage = new javax.swing.JLabel();
        memberFirstName = new javax.swing.JLabel();
        memberLastName = new javax.swing.JLabel();
        memberJoinedDate = new javax.swing.JLabel();
        memberPostCode = new javax.swing.JLabel();
        bookingSuccessMessage = new javax.swing.JDialog();
        bookedTitle = new javax.swing.JLabel();
        confirmBookingSuccess = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        staffNumberLabel = new javax.swing.JLabel();
        staffNumberInput = new javax.swing.JTextField();
        secretCodeLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        mainWindowTitle = new javax.swing.JLabel();
        warnMessage = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        secretCodeInput = new javax.swing.JPasswordField();
        staffPanel = new javax.swing.JPanel();
        currentUserLabel = new javax.swing.JLabel();
        staffIdLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        staffIdInput = new javax.swing.JTextField();
        firstNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        newBookingButton = new javax.swing.JButton();
        bookingsTableLabel = new javax.swing.JLabel();
        bookingsListPanel = new javax.swing.JScrollPane();
        bookingsList = new javax.swing.JList<>();
        removeBookingButton = new javax.swing.JButton();
        rankLabel = new javax.swing.JLabel();

        newBookingFrame.setTitle("New Booking");
        newBookingFrame.setBounds(new java.awt.Rectangle(0, 25, 550, 480));
        newBookingFrame.setMinimumSize(new java.awt.Dimension(550, 460));
        newBookingFrame.setPreferredSize(new java.awt.Dimension(531, 460));
        newBookingFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                newBookingFrameWindowClosing(evt);
            }
        });

        newBookingDateLabel.setText("Booking Date:");

        newBookingTimeLabel.setText("Booking Time:");

        newBookingMemberNameLabel.setText("Member Name:");

        newBookingDateInput.setEditable(false);

        newBookingMemberNameInput.setEditable(false);

        newBookingTimeInput.setEditable(false);

        newBookingMemberIdLabel.setText("Member Id:");

        createNewBookingTitle.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        createNewBookingTitle.setText("Create a new Booking");

        confirmPaid.setText("The member has paid for this booking.");

        fetchUserButton.setText("Get Member");
        fetchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchUserButtonActionPerformed(evt);
            }
        });

        memberValid.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        memberValid.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout newBookingPanelLayout = new javax.swing.GroupLayout(newBookingPanel);
        newBookingPanel.setLayout(newBookingPanelLayout);
        newBookingPanelLayout.setHorizontalGroup(
            newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newBookingPanelLayout.createSequentialGroup()
                        .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newBookingMemberNameLabel)
                                .addComponent(newBookingDateLabel))
                            .addGroup(newBookingPanelLayout.createSequentialGroup()
                                .addComponent(newBookingTimeLabel)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newBookingMemberNameInput)
                            .addComponent(newBookingDateInput)
                            .addComponent(newBookingTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newBookingPanelLayout.createSequentialGroup()
                        .addComponent(confirmPaid)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(newBookingPanelLayout.createSequentialGroup()
                        .addComponent(fetchUserButton)
                        .addGap(18, 18, 18)
                        .addComponent(memberValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newBookingPanelLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newBookingPanelLayout.createSequentialGroup()
                            .addComponent(createNewBookingTitle)
                            .addGap(33, 33, 33))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingPanelLayout.createSequentialGroup()
                            .addComponent(newBookingMemberIdLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                            .addComponent(newBookingMemberIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        newBookingPanelLayout.setVerticalGroup(
            newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fetchUserButton)
                    .addComponent(memberValid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingMemberNameLabel)
                    .addComponent(newBookingMemberNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingDateLabel)
                    .addComponent(newBookingDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingTimeLabel)
                    .addComponent(newBookingTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(confirmPaid))
            .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newBookingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(createNewBookingTitle)
                    .addGap(18, 18, 18)
                    .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newBookingMemberIdLabel)
                        .addComponent(newBookingMemberIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(168, Short.MAX_VALUE)))
        );

        newBookingConfirmButton.setText("Confirm");
        newBookingConfirmButton.setEnabled(false);
        newBookingConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingConfirmButtonActionPerformed(evt);
            }
        });

        newBookingCancelButton.setText("Cancel");
        newBookingCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingCancelButtonActionPerformed(evt);
            }
        });

        newBookingFirstNameLabel.setText("First Name:");

        newBookingLastNameLabel.setText("Last Name:");

        newBookingJoinedInLabel.setText("Joined In:");

        newBookingPostCodeLabel.setText("Post Code:");

        newBookingWarningMessage.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        newBookingWarningMessage.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout newBookingFrameLayout = new javax.swing.GroupLayout(newBookingFrame.getContentPane());
        newBookingFrame.getContentPane().setLayout(newBookingFrameLayout);
        newBookingFrameLayout.setHorizontalGroup(
            newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFrameLayout.createSequentialGroup()
                .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newBookingFrameLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newBookingPostCodeLabel)
                            .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(newBookingFrameLayout.createSequentialGroup()
                                    .addComponent(newBookingConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(newBookingFirstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(newBookingLastNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(newBookingFrameLayout.createSequentialGroup()
                                    .addComponent(newBookingCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newBookingJoinedInLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberFirstName)
                            .addComponent(memberLastName)
                            .addComponent(memberJoinedDate)
                            .addComponent(memberPostCode))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingFrameLayout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBookingWarningMessage)
                            .addComponent(newBookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        newBookingFrameLayout.setVerticalGroup(
            newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newBookingWarningMessage)
                .addGap(18, 18, 18)
                .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newBookingFrameLayout.createSequentialGroup()
                        .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newBookingFirstNameLabel)
                            .addComponent(memberFirstName))
                        .addGap(14, 14, 14)
                        .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newBookingLastNameLabel)
                            .addComponent(memberLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newBookingJoinedInLabel)
                            .addComponent(memberJoinedDate)))
                    .addGroup(newBookingFrameLayout.createSequentialGroup()
                        .addComponent(newBookingConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newBookingCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingPostCodeLabel)
                    .addComponent(memberPostCode))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        bookingSuccessMessage.setBackground(new java.awt.Color(204, 204, 255));
        bookingSuccessMessage.setSize(new java.awt.Dimension(333, 192));

        bookedTitle.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        bookedTitle.setForeground(new java.awt.Color(0, 204, 0));
        bookedTitle.setText("Successfully Booked!");

        confirmBookingSuccess.setText("OK");
        confirmBookingSuccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingSuccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingSuccessMessageLayout = new javax.swing.GroupLayout(bookingSuccessMessage.getContentPane());
        bookingSuccessMessage.getContentPane().setLayout(bookingSuccessMessageLayout);
        bookingSuccessMessageLayout.setHorizontalGroup(
            bookingSuccessMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingSuccessMessageLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(bookingSuccessMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmBookingSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookedTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        bookingSuccessMessageLayout.setVerticalGroup(
            bookingSuccessMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingSuccessMessageLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bookedTitle)
                .addGap(18, 18, 18)
                .addComponent(confirmBookingSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holloway Rugby");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        loginPanel.setPreferredSize(new java.awt.Dimension(435, 300));

        staffNumberLabel.setText("Staff Number");

        staffNumberInput.setToolTipText("");

        secretCodeLabel.setText("Staff Secret Code");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        mainWindowTitle.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        mainWindowTitle.setText("Holloway Rugby Staff Zone");

        warnMessage.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        warnMessage.setForeground(new java.awt.Color(255, 0, 51));

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staffNumberLabel)
                    .addComponent(secretCodeLabel)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(warnMessage))
                    .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainWindowTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffNumberInput)
                    .addComponent(secretCodeInput))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mainWindowTitle)
                .addGap(18, 18, 18)
                .addComponent(staffNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(secretCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secretCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warnMessage))
                        .addGap(30, 30, 30))
                    .addComponent(quitButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        staffPanel.setVerifyInputWhenFocusTarget(false);

        currentUserLabel.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        currentUserLabel.setText("Current Staff");

        staffIdLabel.setText("Staff ID:");

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        emailLabel.setText("Email:");

        staffIdInput.setEditable(false);

        firstNameInput.setEditable(false);

        lastNameInput.setEditable(false);

        emailInput.setEditable(false);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        newBookingButton.setText("New Booking");
        newBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingButtonActionPerformed(evt);
            }
        });

        bookingsTableLabel.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        bookingsTableLabel.setText("Current Bookings");

        bookingsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = bookings.bookingsIds();
            //    public int getSize() { return strings.length; }
            public int getSize() { return bookings.bookingList.size(); }
            public String getElementAt(int i) { return strings[i]; }
        });
        bookingsListPanel.setViewportView(bookingsList);

        removeBookingButton.setForeground(new java.awt.Color(204, 0, 51));
        removeBookingButton.setText("Remove Booking");
        removeBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookingButtonActionPerformed(evt);
            }
        });

        rankLabel.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        rankLabel.setForeground(new java.awt.Color(51, 153, 0));
        rankLabel.setText("rank");

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameLabel)
                    .addComponent(currentUserLabel)
                    .addComponent(firstNameLabel)
                    .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(staffPanelLayout.createSequentialGroup()
                            .addComponent(rankLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutButton))
                        .addGroup(staffPanelLayout.createSequentialGroup()
                            .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(staffIdLabel)
                                .addComponent(emailLabel))
                            .addGap(68, 68, 68)
                            .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(staffIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffPanelLayout.createSequentialGroup()
                        .addComponent(bookingsTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(staffPanelLayout.createSequentialGroup()
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookingsListPanel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffPanelLayout.createSequentialGroup()
                                .addComponent(newBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeBookingButton)
                                .addGap(0, 77, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(staffPanelLayout.createSequentialGroup()
                        .addComponent(bookingsTableLabel)
                        .addGap(20, 20, 20)
                        .addComponent(bookingsListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffPanelLayout.createSequentialGroup()
                        .addComponent(currentUserLabel)
                        .addGap(18, 18, 18)
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffIdLabel)
                            .addComponent(staffIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutButton)
                            .addComponent(rankLabel))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(staffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
        if(staffNumberInput.getText().isEmpty()) {
            warnMessage.setText("Please enter a Staff ID.");
            return;
        }
        if(secretCodeInput.getText().isEmpty()) {
            warnMessage.setText("Please enter your Secret Code.");
            return;
        }
        
        try {
            staffId = Integer.parseInt(staffNumberInput.getText());
        } catch (NumberFormatException e) {
            warnMessage.setText("Wrong Staff ID. Has to be a number.");
            return;
        }
        
        try {
            secretCode = Integer.parseInt(secretCodeInput.getText());
        } catch (NumberFormatException e) {
            warnMessage.setText("Wrong Secret Code. Has to be a number.");
            return;
        }

        staff.staffList.forEach( (staff) -> {
            if(staff.getStaffID() == staffId && staff.getSecretCode() == secretCode) {
                firstName = staff.getFirstName();
                lastName = staff.getLastName();
                email = staff.getEmail();
                rankLabel.setText(staff.getRank());
                staffExists = true;
                warnMessage.setText("");
            }
        });

        if(!staffExists) {
            warnMessage.setText("No user found with those details");
            return;
        }

        loginPanel.setVisible(false); // hide the panel with the login form
        staffPanel.setVisible(true); // set the staff panel to visible when a valid staff is found

        staffIdInput.setText(String.valueOf(staffId));
        firstNameInput.setText(firstName);
        lastNameInput.setText(lastName);
        emailInput.setText(email);

        /**
         * Reset input boxes.
         */
        staffNumberInput.setText("");
        secretCodeInput.setText("");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_quitButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        staffPanel.setVisible(false);

        staffIdInput.setText("");
        firstNameInput.setText("");
        lastNameInput.setText("");
        emailInput.setText("");

        loginPanel.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void newBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingButtonActionPerformed
        // TODO add your handling code here:
        newBookingFrame.setVisible(true);
    }//GEN-LAST:event_newBookingButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        staffPanel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void confirmBookingSuccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingSuccessActionPerformed
        // TODO add your handling code here:
        
        newBookingMemberIdInput.setText("");
        newBookingMemberNameInput.setText("");
        newBookingDateInput.setText("");
        newBookingTimeInput.setText("");
        
        newBookingFrame.setVisible(false);
        newBookingWarningMessage.setText("");
        confirmPaid.setSelected(false);
        
        memberValid.setText("");
        
        memberFirstName.setText("");
        memberLastName.setText("");
        memberJoinedDate.setText("");
        memberPostCode.setText("");
        
        bookingSuccessMessage.setVisible(false);
    }//GEN-LAST:event_confirmBookingSuccessActionPerformed

    private void removeBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookingButtonActionPerformed
        // TODO add your handling code here:
        bookings.bookingList.remove(bookingsList.getSelectedIndex());
        
        updateBookingList();
    }//GEN-LAST:event_removeBookingButtonActionPerformed

    private void newBookingCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingCancelButtonActionPerformed
        // TODO add your handling code here:

        newBookingMemberIdInput.setText("");
        newBookingMemberNameInput.setText("");
        newBookingDateInput.setText("");
        newBookingTimeInput.setText("");

        newBookingFrame.setVisible(false);
        newBookingWarningMessage.setText("");
        memberValid.setText("");
        
        memberFirstName.setText("");
        memberLastName.setText("");
        memberJoinedDate.setText("");
        memberPostCode.setText("");
    }//GEN-LAST:event_newBookingCancelButtonActionPerformed

    private void newBookingConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingConfirmButtonActionPerformed
        // TODO add your handling code here:

        newBookingMemberId = newBookingMemberIdInput.getText();
        newBookingMemberName = newBookingMemberNameInput.getText();
        newBookingDate = newBookingDateInput.getText();
        newBookingTime = newBookingTimeInput.getText();

        if(newBookingMemberId.trim().isEmpty()) {
            newBookingWarningMessage.setText("Please enter a Member ID.");
            return;
        }
        if(newBookingMemberName.trim().isEmpty()) {
            newBookingWarningMessage.setText("Please enter a Member Name.");
            return;
        }
        if(newBookingDate.trim().isEmpty()) {
            newBookingWarningMessage.setText("Please enter a date.");
            return;
        }
        if(newBookingTime.trim().isEmpty()) {
            newBookingWarningMessage.setText("Please enter a time.");
            return;
        }

        // date and time format checker
        String datePattern = "[0-9]{2}\\/[0-9]{2}\\/[0-9]{2}";
        String hourPattern = "[0-9]{2}\\:[0-9]{2}";
        if(!newBookingDate.matches(datePattern)) {
            newBookingWarningMessage.setText("Invalid date format. 00/00/00");
            return;
        }
        if(!newBookingTime.matches(hourPattern)) {
            newBookingWarningMessage.setText("Invalid time format. 00:00");
            return;
        }

        if(!confirmPaid.isSelected()) {
            newBookingWarningMessage.setText("Please confirm that the booking is paid for.");
            return;
        }

        //add a new booking
        bookings.addBooking(
            newBookingMemberIdInput.getText(),
            newBookingMemberNameInput.getText(),
            newBookingDateInput.getText(),
            newBookingTimeInput.getText()
        );

        updateBookingList();

        bookingSuccessMessage.setVisible(true);

    }//GEN-LAST:event_newBookingConfirmButtonActionPerformed

    private void fetchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchUserButtonActionPerformed
        // TODO add your handling code here:
        memberExists = false;

        //timer task to reset warning message
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                newBookingWarningMessage.setText("");
            }
        };
        timer.schedule(task, 4000);

        newBookingMemberId = newBookingMemberIdInput.getText();

        if(newBookingMemberId.trim().isEmpty()) {
            newBookingWarningMessage.setText("Please enter a Member ID.");
            return;
        }

        members.membersList.forEach( (member) -> {
            if(member.getMemberId().equals(newBookingMemberId)) {
                if(member.getMemberStatus()) {
                    
                    memberFirstName.setText(member.getFirstName());
                    memberLastName.setText(member.getLastName());
                    memberJoinedDate.setText(member.getJoinedDate());
                    memberPostCode.setText(member.getPostCode());
                    
                    if(member.getOrganizerStatus()) {
                        newBookingMemberNameInput.setText(member.getFirstName());
                        newBookingDateInput.setEditable(true);
                        newBookingDateInput.setText("__/__/__");
                        newBookingTimeInput.setEditable(true);
                        newBookingTimeInput.setText("__:__");
                        newBookingConfirmButton.setEnabled(true);
                        memberValid.setText("Active Member.");
                        memberValid.setForeground(new java.awt.Color(0, 128, 9));
                    } else {
                        memberValid.setText("Not team organizer.");
                        memberValid.setForeground(new java.awt.Color(255, 0, 51));
                        newBookingMemberNameInput.setText("");
                        newBookingDateInput.setEditable(false);
                        newBookingDateInput.setText("");
                        newBookingTimeInput.setEditable(false);
                        newBookingTimeInput.setText("");
                        newBookingConfirmButton.setEnabled(false);
                    }
                } else {
                    memberValid.setText("Inactive Member.");
                    memberValid.setForeground(new java.awt.Color(255, 0, 51));
                    newBookingMemberNameInput.setText("");
                    newBookingDateInput.setEditable(false);
                    newBookingDateInput.setText("");
                    newBookingTimeInput.setEditable(false);
                    newBookingTimeInput.setText("");
                    newBookingConfirmButton.setEnabled(false);
                }

                memberExists = true;
            }
        });

        if(!memberExists) {
            newBookingWarningMessage.setText("No member found with that ID.");
            newBookingMemberNameInput.setText("");
            newBookingDateInput.setEditable(false);
            newBookingDateInput.setText("");
            newBookingTimeInput.setEditable(false);
            newBookingTimeInput.setText("");
            newBookingConfirmButton.setEnabled(false);
            memberValid.setText("");
            return;
        }
    }//GEN-LAST:event_fetchUserButtonActionPerformed

    private void newBookingFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_newBookingFrameWindowClosing
        // TODO add your handling code here:

        newBookingMemberIdInput.setText("");
        newBookingMemberNameInput.setText("");
        newBookingDateInput.setText("");
        newBookingTimeInput.setText("");

        newBookingFrame.setVisible(false);
        newBookingWarningMessage.setText("");
        memberValid.setText("");
        
        memberFirstName.setText("");
        memberLastName.setText("");
        memberJoinedDate.setText("");
        memberPostCode.setText("");
    }//GEN-LAST:event_newBookingFrameWindowClosing

    private void updateBookingList() {
        //update list
        bookingsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = bookings.bookingsIds();
            //    public int getSize() { return strings.length; }
            public int getSize() { return bookings.bookingList.size(); }
            public String getElementAt(int i) { return strings[i]; }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    /**
     * Exit method
     */
    void exit() {
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookedTitle;
    private javax.swing.JDialog bookingSuccessMessage;
    private javax.swing.JList<String> bookingsList;
    private javax.swing.JScrollPane bookingsListPanel;
    private javax.swing.JLabel bookingsTableLabel;
    private javax.swing.JButton confirmBookingSuccess;
    private javax.swing.JCheckBox confirmPaid;
    private javax.swing.JLabel createNewBookingTitle;
    private javax.swing.JLabel currentUserLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton fetchUserButton;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mainWindowTitle;
    private javax.swing.JLabel memberFirstName;
    private javax.swing.JLabel memberJoinedDate;
    private javax.swing.JLabel memberLastName;
    private javax.swing.JLabel memberPostCode;
    private javax.swing.JLabel memberValid;
    private javax.swing.JButton newBookingButton;
    private javax.swing.JButton newBookingCancelButton;
    private javax.swing.JButton newBookingConfirmButton;
    private javax.swing.JTextField newBookingDateInput;
    private javax.swing.JLabel newBookingDateLabel;
    private javax.swing.JLabel newBookingFirstNameLabel;
    private javax.swing.JFrame newBookingFrame;
    private javax.swing.JLabel newBookingJoinedInLabel;
    private javax.swing.JLabel newBookingLastNameLabel;
    private javax.swing.JTextField newBookingMemberIdInput;
    private javax.swing.JLabel newBookingMemberIdLabel;
    private javax.swing.JTextField newBookingMemberNameInput;
    private javax.swing.JLabel newBookingMemberNameLabel;
    private javax.swing.JPanel newBookingPanel;
    private javax.swing.JLabel newBookingPostCodeLabel;
    private javax.swing.JTextField newBookingTimeInput;
    private javax.swing.JLabel newBookingTimeLabel;
    private javax.swing.JLabel newBookingWarningMessage;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel rankLabel;
    private javax.swing.JButton removeBookingButton;
    private javax.swing.JPasswordField secretCodeInput;
    private javax.swing.JLabel secretCodeLabel;
    private javax.swing.JTextField staffIdInput;
    private javax.swing.JLabel staffIdLabel;
    private javax.swing.JTextField staffNumberInput;
    private javax.swing.JLabel staffNumberLabel;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JLabel warnMessage;
    // End of variables declaration//GEN-END:variables
}
